# Generated by Django 4.0.4 on 2022-05-19 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_students'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['-gpa']},
        ),
    ]
