# Generated by Django 4.0.4 on 2022-05-19 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_students_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='course1_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='course2_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='course3_id',
            field=models.IntegerField(null=True),
        ),
    ]
