# Generated by Django 4.0.4 on 2022-05-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_students_course1_id_students_course2_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('dep', models.CharField(max_length=20)),
                ('n_hours', models.IntegerField()),
                ('hall_number', models.IntegerField()),
                ('lectue_day', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='students',
            name='course1_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='course2_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='course3_id',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='students',
            name='register',
            field=models.ManyToManyField(to='catalog.courses'),
        ),
    ]
