# Generated by Django 4.0.4 on 2022-05-19 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_courses_id_alter_students_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='course1_id',
        ),
        migrations.RemoveField(
            model_name='students',
            name='course2_id',
        ),
        migrations.RemoveField(
            model_name='students',
            name='course3_id',
        ),
    ]
