# Generated by Django 4.0.4 on 2022-05-20 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_students_course1_students_course2_students_course3'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='university',
            field=models.CharField(default='Cairo University', max_length=20),
        ),
    ]
