# Generated by Django 4.0.4 on 2022-05-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20220524_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='dep',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='hall_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='lectue_day',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='n_hours',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
