# Generated by Django 4.0.4 on 2022-05-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_courses_dep_alter_courses_hall_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Student', max_length=20)),
                ('ID', models.CharField(max_length=8)),
            ],
            options={
                'ordering': ['ID'],
            },
        ),
    ]
