# Generated by Django 4.0.4 on 2022-05-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='id',
        ),
        migrations.AlterField(
            model_name='registration',
            name='ID',
            field=models.CharField(max_length=8, primary_key=b'I01\n', serialize=False),
        ),
    ]
