# Generated by Django 4.0.4 on 2022-05-24 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_registration_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Catalog',
        ),
        migrations.DeleteModel(
            name='Node',
        ),
    ]
