# Generated by Django 4.0.4 on 2022-05-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_delete_catalog_delete_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='student_ID',
            field=models.CharField(max_length=9, primary_key=b'I01\n', serialize=False),
        ),
    ]
