# Generated by Django 4.0.4 on 2022-05-24 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_alter_registration_student_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='students',
            old_name='ID',
            new_name='id',
        ),
    ]
