# Generated by Django 4.0.4 on 2022-05-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_delete_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('name', models.CharField(default='Student', max_length=20)),
                ('student_ID', models.CharField(max_length=9, primary_key=b'I01\n', serialize=False)),
            ],
            options={
                'ordering': ['student_ID'],
            },
        ),
    ]
